---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: Update the apt-cache, if necessary
      apt:
        update_cache: true
        cache_valid_time: 86400
      when: ansible_facts['os_family'] == 'Debian'
  roles:
    - geerlingguy.docker
